spring.application.name=media-upload-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/media_db
spring.datasource.username=postgres
spring.datasource.password=postgres


spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true


spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test
spring.cloud.aws.s3.endpoint=http://localhost:4566
spring.cloud.aws.s3.path-style-access-enabled=true


app.s3.bucket=media-bucket
app.s3.create-bucket-on-startup=true


spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Error handling configuration
error.handling.http-status-in-json-response=true
error.handling.http-statuses.java.lang.IllegalArgumentException=BAD_REQUEST
error.handling.codes.java.lang.IllegalArgumentException=BAD_REQUEST
error.handling.http-statuses.software.amazon.awssdk.services.s3.model.NoSuchKeyException=NOT_FOUND
error.handling.codes.software.amazon.awssdk.services.s3.model.NoSuchKeyException=MEDIA_FILE_NOT_FOUND
error.handling.messages.software.amazon.awssdk.services.s3.model.NoSuchKeyException=Media file not found in storage
error.handling.http-statuses.java.io.IOException=INTERNAL_SERVER_ERROR
error.handling.messages.java.io.IOException=Error processing media file